version: 2

updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - '*'
    ignore:
      - dependency-name: 'typescript'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
