import { defineConfig } from 'oxlint';

export default defineConfig({
  plugins: ['typescript', 'unicorn', 'import', 'vue', 'oxc'],
  categories: {
    correctness: 'error',
    suspicious: 'warn',
    perf: 'warn',
  },
  rules: {
    'no-console': [
      'warn',
      {
        allow: ['warn', 'error', 'info'],
      },
    ],
    'no-debugger': 'error',
    'no-var': 'error',
    'prefer-const': 'error',
    'eslint/no-unused-vars': [
      'error',
      {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
      },
    ],

    'typescript/no-floating-promises': 'error',
    'typescript/no-misused-promises': 'error',
    'typescript/await-thenable': 'error',
    'typescript/no-unsafe-assignment': 'warn',
    'typescript/require-await': 'warn',
    'typescript/restrict-template-expressions': 'warn',
    'typescript/unbound-method': 'error',
    'typescript/switch-exhaustiveness-check': 'warn',
    'typescript/prefer-nullish-coalescing': 'warn',
    'typescript/prefer-optional-chain': 'warn',
    'typescript/no-explicit-any': 'warn',
    'typescript/no-non-null-assertion': 'warn',
    'typescript/consistent-type-imports': 'warn',
    'typescript/consistent-type-exports': 'warn',
    'typescript/no-import-type-side-effects': 'error',
    'typescript/no-duplicate-enum-values': 'error',
    'typescript/no-duplicate-type-constituents': 'error',
    'typescript/no-redundant-type-constituents': 'error',
    'typescript/no-misused-spread': 'error',
    'typescript/no-base-to-string': 'error',
    'typescript/no-array-delete': 'error',
    'typescript/no-for-in-array': 'error',
    'typescript/no-meaningless-void-operator': 'error',
    'typescript/no-confusing-non-null-assertion': 'warn',
    'typescript/no-confusing-void-expression': 'warn',
    'typescript/ban-ts-comment': 'warn',
    'typescript/consistent-generic-constructors': 'warn',
    'typescript/consistent-indexed-object-style': 'warn',
    'typescript/array-type': 'warn',
    'typescript/no-inferrable-types': 'warn',
    'typescript/no-empty-object-type': 'warn',
    'typescript/no-invalid-void-type': 'warn',
    'typescript/no-dynamic-delete': 'warn',
    'typescript/no-namespace': 'warn',
    'typescript/no-require-imports': 'warn',
    'typescript/adjacent-overload-signatures': 'warn',

    'vue/no-dupe-keys': 'error',
    'vue/no-deprecated-data-object-declaration': 'error',
    'vue/no-deprecated-delete-set': 'error',
    'vue/no-deprecated-destroyed-lifecycle': 'error',
    'vue/no-deprecated-events-api': 'error',
    'vue/no-deprecated-model-definition': 'error',
    'vue/no-deprecated-props-default-this': 'error',
    'vue/no-deprecated-vue-config-keycodes': 'error',
    'vue/no-async-in-computed-properties': 'error',
    'vue/no-side-effects-in-computed-properties': 'error',
    'vue/no-computed-properties-in-data': 'error',
    'vue/no-lifecycle-after-await': 'error',
    'vue/no-expose-after-await': 'error',
    'vue/no-arrow-functions-in-watch': 'error',
    'vue/no-export-in-script-setup': 'error',
    'vue/no-reserved-component-names': 'error',
    'vue/no-reserved-keys': 'error',
    'vue/no-reserved-props': 'error',
    'vue/no-required-prop-with-default': 'warn',
    'vue/no-shared-component-data': 'error',
    'vue/no-multiple-slot-args': 'error',
    'vue/no-import-compiler-macros': 'warn',
    'vue/define-props-declaration': 'warn',
    'vue/define-emits-declaration': 'warn',
    'vue/next-tick-style': 'warn',
    'vue/component-definition-name-casing': 'warn',

    'unicorn/no-instanceof-array': 'warn',
    'unicorn/no-invalid-fetch-options': 'error',
    'unicorn/no-invalid-remove-event-listener': 'error',
    'unicorn/no-thenable': 'error',
    'unicorn/no-await-in-promise-methods': 'error',
    'unicorn/catch-error-name': 'warn',
    'unicorn/error-message': 'warn',
    'unicorn/no-new-array': 'warn',
    'unicorn/no-null': 'off',

    'import/no-duplicates': 'error',
    'import/no-cycle': 'warn',
    'import/no-self-import': 'error',
    'import/no-mutable-exports': 'warn',
    'import/newline-after-import': 'warn',
  },
  options: {
    typeAware: true,
    typeCheck: true,
  },
  ignorePatterns: ['**.d.ts'],
});
